apiVersion: apps/v1
kind: Deployment
metadata:
  name: snakebin
spec:
  selector:
    matchLabels:
      app: flask
  replicas: 1
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: snakebin
        image: rpolve:snakebin
        ports:
          - containerPort: 8089
---
apiVersion: v1
kind: Service
metadata:
  name: snakebin
spec:
  ports:
  - port: 8089
    targetPort: 8089
    nodePort: 31110
    name: http
  selector:
    app: flask
