"""empty message

Revision ID: 5a9c0f7e8713
Revises: 
Create Date: 2020-12-14 23:09:40.435042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a9c0f7e8713'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('complete', sa.Boolean(), nullable=True),
    sa.Column('elapsed', sa.Integer(), nullable=True),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('submitted', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_job_title'), 'job', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_title'), table_name='job')
    op.drop_table('job')
    # ### end Alembic commands ###
